### ISSUE TITLE
cron.php failing

### ISSUE THREAD

**Issue by dg01d** [aaronpk/Watchtower#4]
Fresh installation of watchtower, pulled from github this morning

Followed my own installation instructions

cron.php is failing with:

```
PHP Warning:  require(/srv/watchtower/vendor/composer/../../lib/config.php): failed to open stream: No such file or directory in /srv/watchtower/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/srv/watchtower/vendor/composer/../../lib/config.php' (include_path='.:/usr/share/php') in /srv/watchtower/vendor/composer/autoload_real.php on line 66
```

**Comment by aaronpk** [comment]
I of course don't have any docs for this yet, but you just need to copy `lib/config.template.php` to `lib/config.php` and fill out the values.

**Comment by dg01d** [comment]
d'oh!

done, and added to my installation instructions.
